# Cloud Build: build e deploy da API no Cloud Run
steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-api'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$YOUR_PROJECT_ID/airbnb-optimizer/api:$COMMIT_SHA'
      - '-f'
      - 'docker/api/Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-api'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$YOUR_PROJECT_ID/airbnb-optimizer/api:$COMMIT_SHA'
    waitFor: ['build-api']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-api'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'airbnb-price-api'
      - '--image=us-central1-docker.pkg.dev/$YOUR_PROJECT_ID/airbnb-optimizer/api:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--min-instances=0'
      - '--max-instances=5'
      - '--set-env-vars=GCP_YOUR_PROJECT_ID=$YOUR_PROJECT_ID,GCP_BUCKET_NAME=airbnb-price-optimizer'
    waitFor: ['push-api']

images:
  - 'us-central1-docker.pkg.dev/$YOUR_PROJECT_ID/airbnb-optimizer/api:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
