apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: airbnb-price-api
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 60
      containers:
        - image: us-central1-docker.pkg.dev/project-b0fa2d28-630e-4922-b41/airbnb-optimizer/api:latest
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
          env:
            - name: ENVIRONMENT
              value: production
            - name: MODEL_PATH
              value: models/model.joblib
            - name: ENCODERS_PATH
              value: models/encoders.joblib
            - name: PROCESSED_DATA_PATH
              value: data/processed
            - name: API_KEYS_RAW
              value: ""
          livenessProbe:
            httpGet:
              path: /health
            initialDelaySeconds: 15
            periodSeconds: 30
